name: Deploy container to ECS
on:
  push:
    branches: [ master ]

job:
  deploy:
    steps:
      - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
      
      - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition sidebar-image-on-docker-hub --query taskDefinition > task-definition.json
      
      - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        cluster: sidebar-cluster
